# Generated by Django 5.0.6 on 2024-05-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='temperature',
            field=models.IntegerField(blank=True),
        ),
    ]
